from datetime import datetime, timezone
from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column
from app.db.session import Base

def now(): return datetime.now(timezone.utc)
class Store(Base):
    __tablename__="stores"; id:Mapped[str]=mapped_column(String,primary_key=True); name:Mapped[str]=mapped_column(String); location:Mapped[str]=mapped_column(String); status:Mapped[str]=mapped_column(String,default="online"); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Zone(Base):
    __tablename__="zones"; id:Mapped[str]=mapped_column(String,primary_key=True); store_id:Mapped[str]=mapped_column(ForeignKey("stores.id")); name:Mapped[str]=mapped_column(String); type:Mapped[str]=mapped_column(String); status:Mapped[str]=mapped_column(String,default="normal"); occupancy:Mapped[int]=mapped_column(Integer,default=0); average_dwell_seconds:Mapped[int]=mapped_column(Integer,default=0)
class Camera(Base):
    __tablename__="cameras"; id:Mapped[str]=mapped_column(String,primary_key=True); store_id:Mapped[str]=mapped_column(ForeignKey("stores.id")); zone_id:Mapped[str]=mapped_column(ForeignKey("zones.id")); name:Mapped[str]=mapped_column(String); status:Mapped[str]=mapped_column(String,default="online"); stream_health:Mapped[str]=mapped_column(String,default="good"); visibility_score:Mapped[float]=mapped_column(Float,default=100); analytics_confidence:Mapped[float]=mapped_column(Float,default=1); last_seen_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Shelf(Base):
    __tablename__="shelves"; id:Mapped[str]=mapped_column(String,primary_key=True); store_id:Mapped[str]=mapped_column(ForeignKey("stores.id")); zone_id:Mapped[str]=mapped_column(ForeignKey("zones.id")); shelf_code:Mapped[str]=mapped_column(String,index=True); product_name:Mapped[str]=mapped_column(String); sku:Mapped[str]=mapped_column(String); availability_percent:Mapped[float]=mapped_column(Float); status:Mapped[str]=mapped_column(String); depletion_rate:Mapped[float]=mapped_column(Float,default=0); predicted_oos_minutes:Mapped[int|None]=mapped_column(Integer,nullable=True); confidence:Mapped[float]=mapped_column(Float); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Queue(Base):
    __tablename__="queues"; id:Mapped[str]=mapped_column(String,primary_key=True); store_id:Mapped[str]=mapped_column(ForeignKey("stores.id")); counter_name:Mapped[str]=mapped_column(String); status:Mapped[str]=mapped_column(String); current_length:Mapped[int]=mapped_column(Integer); estimated_wait_minutes:Mapped[float]=mapped_column(Float); arrival_rate:Mapped[float]=mapped_column(Float); service_rate:Mapped[float]=mapped_column(Float); predicted_length:Mapped[int]=mapped_column(Integer); prediction_window_minutes:Mapped[int]=mapped_column(Integer); congestion_risk:Mapped[str]=mapped_column(String); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class ShopperMetric(Base):
    __tablename__="shopper_metrics"; id:Mapped[int]=mapped_column(primary_key=True,autoincrement=True); store_id:Mapped[str]=mapped_column(ForeignKey("stores.id")); zone_id:Mapped[str]=mapped_column(ForeignKey("zones.id")); timestamp_window:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); footfall:Mapped[int]=mapped_column(Integer); entries:Mapped[int]=mapped_column(Integer); exits:Mapped[int]=mapped_column(Integer); occupancy:Mapped[int]=mapped_column(Integer); average_dwell_seconds:Mapped[int]=mapped_column(Integer); peak_occupancy:Mapped[int]=mapped_column(Integer)
class Alert(Base):
    __tablename__="alerts"; id:Mapped[str]=mapped_column(String,primary_key=True); store_id:Mapped[str]=mapped_column(ForeignKey("stores.id")); source_type:Mapped[str]=mapped_column(String); source_id:Mapped[str]=mapped_column(String); severity:Mapped[str]=mapped_column(String); title:Mapped[str]=mapped_column(String); message:Mapped[str]=mapped_column(Text); status:Mapped[str]=mapped_column(String,default="open"); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); acknowledged_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)
class Prediction(Base):
    __tablename__="predictions"; id:Mapped[str]=mapped_column(String,primary_key=True); type:Mapped[str]=mapped_column(String); source_id:Mapped[str]=mapped_column(String); predicted_value:Mapped[str]=mapped_column(String); prediction_window:Mapped[int]=mapped_column(Integer); confidence:Mapped[float]=mapped_column(Float); explanation:Mapped[str]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Recommendation(Base):
    __tablename__="recommendations"; id:Mapped[str]=mapped_column(String,primary_key=True); store_id:Mapped[str]=mapped_column(ForeignKey("stores.id")); prediction_id:Mapped[str|None]=mapped_column(ForeignKey("predictions.id"),nullable=True); title:Mapped[str]=mapped_column(String); action:Mapped[str]=mapped_column(String); reason:Mapped[str]=mapped_column(Text); priority:Mapped[str]=mapped_column(String); expected_outcome:Mapped[str]=mapped_column(String); status:Mapped[str]=mapped_column(String,default="recommended")
class ActionTask(Base):
    __tablename__="actions"; id:Mapped[str]=mapped_column(String,primary_key=True); recommendation_id:Mapped[str|None]=mapped_column(ForeignKey("recommendations.id"),nullable=True); store_id:Mapped[str]=mapped_column(ForeignKey("stores.id")); assigned_to:Mapped[str|None]=mapped_column(String,nullable=True); title:Mapped[str]=mapped_column(String); description:Mapped[str]=mapped_column(Text); type:Mapped[str]=mapped_column(String); priority:Mapped[str]=mapped_column(String); location:Mapped[str]=mapped_column(String); status:Mapped[str]=mapped_column(String); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); accepted_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); started_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); resolution_note:Mapped[str|None]=mapped_column(Text,nullable=True)
class Activity(Base):
    __tablename__="activity"; id:Mapped[int]=mapped_column(primary_key=True,autoincrement=True); store_id:Mapped[str]=mapped_column(ForeignKey("stores.id")); event:Mapped[str]=mapped_column(String); message:Mapped[str]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class EdgeState(Base):
    __tablename__="edge_state"; store_id:Mapped[str]=mapped_column(ForeignKey("stores.id"),primary_key=True); online:Mapped[bool]=mapped_column(Boolean,default=True); analytics_running:Mapped[bool]=mapped_column(Boolean,default=True); pending_events:Mapped[int]=mapped_column(Integer,default=0); metadata_sync_status:Mapped[str]=mapped_column(String,default="active"); storage_percent:Mapped[int]=mapped_column(Integer,default=38); cpu_percent:Mapped[int]=mapped_column(Integer,default=42); npu_percent:Mapped[int]=mapped_column(Integer,default=67); temperature_c:Mapped[int]=mapped_column(Integer,default=54); last_cloud_sync:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class EdgeEventRecord(Base):
    __tablename__="edge_events"; event_id:Mapped[str]=mapped_column(String,primary_key=True); store_id:Mapped[str]=mapped_column(String,index=True); event_type:Mapped[str]=mapped_column(String); received_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
