import { useState } from 'react'
import { Activity, Camera as CameraIcon, Cloud, CloudOff, CloudUpload, Cpu, Database, HardDrive, ShieldCheck, Thermometer, Wifi, WifiOff } from 'lucide-react'
import { cameras } from '../../data/cameras'
import { edgeHealth as e } from '../../data/edgeHealth'
import { Card, DButton, PageHeader, SectionHeader, StatusBadge } from '../../components/dashboard/ui'

export default function EdgeHealth() {
  const [offline, setOffline] = useState(false), [pending, setPending] = useState(e.pending)
  const reconnect = () => { setOffline(false); setPending(0) }
  const systems = offline ? [
    ['Edge node', e.node, 'Online', Cpu], ['Internet', 'Offline', 'Cloud connection paused', WifiOff], ['Cloud sync', 'Paused', `${pending} metadata events pending`, CloudOff], ['Local analytics', 'Running', 'On-device inference active', Activity],
  ] : [['Edge node', e.node, 'Online', Cpu], ['Internet', 'Online', 'Stable', Wifi], ['Cloud sync', pending ? 'Syncing' : 'Active', `${pending} metadata events pending`, Cloud], ['Local analytics', 'Running', 'On-device inference active', Activity]] as const
  return <>
    <PageHeader eyebrow="EDGE & PRIVACY HEALTH" title="Edge & privacy health" copy="Verify that local intelligence continues operating even when connectivity is unavailable." actions={<div className="offline-toggle"><span className={offline ? 'toggle-dot off' : 'toggle-dot'} />{offline ? 'Offline demo' : 'Connected'}<DButton variant={offline ? 'primary' : 'secondary'} onClick={() => offline ? reconnect() : setOffline(true)}>{offline ? 'Restore internet' : 'Simulate internet off'}</DButton></div>} />
    {offline && <div className="offline-banner"><WifiOff/><div><b>Internet is OFF — edge analytics continue locally.</b><span>Shelf monitoring, queue monitoring, and local alerts remain active. Cloud sync is paused until connectivity returns.</span></div></div>}
    {!offline && pending === 0 && <div className="sync-banner"><CloudUpload/><b>Pending metadata synced</b><span>All queued operational metadata has reached the cloud.</span></div>}
    <div className="edge-status-grid">{systems.map(([label,value,note,Icon]) => <Card key={label}><Icon/><span>{label}</span><strong>{value}</strong><small>{note}</small></Card>)}</div>
    <section className="overview-section"><SectionHeader title="Local-first operations" copy="Capabilities that remain available during an internet outage."/><div className="offline-capabilities"><Capability label="Shelf monitoring" state="Running"/><Capability label="Queue monitoring" state="Running"/><Capability label="Local alerts" state="Running"/><Capability label="Cloud sync" state={offline ? 'Paused' : 'Active'} paused={offline}/></div></section>
    <section className="overview-section"><SectionHeader title="Privacy telemetry" copy="Auditable signals from the local processing pipeline."/><div className="privacy-telemetry"><Card><CloudUpload/><span>RAW VIDEO UPLOADED</span><strong>0 MB</strong><small>Video remains on premises</small></Card><Card><ShieldCheck/><span>PERSISTENT CUSTOMER IDENTITIES</span><strong>0</strong><small>Anonymous events only</small></Card><Card><Database/><span>METADATA-ONLY SYNC</span><strong>Enabled</strong><small>{offline ? `${pending} events waiting locally` : 'Operational events only'}</small></Card></div></section>
    <section className="overview-section"><SectionHeader title="Edge device resources"/><Card className="util-grid">{[[Cpu,'CPU utilisation',e.cpu,'%'],[Activity,'NPU utilisation',e.npu,'%'],[HardDrive,'Local storage',e.storage,'%'],[Thermometer,'Temperature',e.temperature,'°C']].map(([Icon,l,v,s]) => <div key={String(l)}><Icon/><span>{l}</span><b>{v}{s}</b><div><i style={{width:`${Number(v)}%`}}/></div></div>)}</Card></section>
    <section className="overview-section"><SectionHeader title="Camera health" copy="Current stream quality and scene integrity."/><div className="camera-grid">{cameras.map(c => <Card key={c.id} className={!c.online ? 'camera-offline' : ''}><header><div><small>{c.id}</small><h3>{c.zone}</h3></div><StatusBadge status={!c.online ? 'offline' : c.issue ? 'warning' : 'normal'} label={!c.online ? 'Offline' : c.issue?.toLowerCase().includes('light') ? 'Low light' : c.issue?.toLowerCase().includes('shift') ? 'Scene shifted' : c.issue?.toLowerCase().includes('obstruct') ? 'Obstructed' : 'Online'}/></header><div className="camera-preview"><CameraIcon/><span>{c.online ? 'LOCAL PREVIEW MASKED' : 'STREAM DISCONNECTED'}</span></div><dl><div><dt>Stream health</dt><dd>{c.stream}</dd></div><div><dt>Visibility</dt><dd>{c.visibility}%</dd></div><div><dt>AI confidence</dt><dd>{c.confidence}%</dd></div></dl>{c.issue&&<footer>{c.issue}</footer>}</Card>)}</div></section>
  </>
}
function Capability({label,state,paused=false}:{label:string;state:string;paused?:boolean}) { return <Card className={paused?'capability paused':''}><span className="cap-dot"/><div><b>{label}</b><small>{state}</small></div></Card> }
