import { useMemo,useState } from 'react'
import { Boxes,PackageCheck,PackageMinus,ScanLine } from 'lucide-react'
import { shelves } from '../../data/shelves'
import type { Shelf } from '../../types/dashboard'
import { KpiCard } from '../../components/dashboard/KpiCard'
import { Card,DButton,Modal,PageHeader,SearchInput,Select,StatusBadge } from '../../components/dashboard/ui'
import { MiniChart } from '../../components/dashboard/Charts'
export default function Shelves(){const [search,setSearch]=useState(''),[status,setStatus]=useState('all'),[selected,setSelected]=useState<Shelf|null>(null);const rows=useMemo(()=>shelves.filter(s=>(status==='all'||s.status===status)&&(s.product+s.id+s.zone).toLowerCase().includes(search.toLowerCase())),[search,status]);return <><PageHeader eyebrow="SHELF INTELLIGENCE" title="Shelves" copy="Detect availability issues and act before products disappear." actions={<DButton>+ Add monitor</DButton>}/><div className="compact-kpis"><KpiCard label="Monitored Shelves" value="84" note="Across 5 zones" icon={Boxes}/><KpiCard label="Healthy Shelves" value="72" note="85.7%" icon={PackageCheck}/><KpiCard label="Low Stock" value="7" note="3 critical" icon={PackageMinus} tone="amber"/><KpiCard label="Out of Stock" value="2" note="Action required" icon={PackageMinus} tone="red"/><KpiCard label="Planogram Issues" value="3" note="Review today" icon={ScanLine} tone="violet"/></div><Card className="filters"><SearchInput value={search} onChange={setSearch} placeholder="Search shelf or product"/><Select label="Status" value={status} onChange={setStatus}><option value="all">All statuses</option><option value="critical">Critical</option><option value="warning">Warning</option><option value="normal">Normal</option></Select><Select label="Zone" value="all" onChange={()=>{}}><option>All zones</option></Select><Select label="Category" value="all" onChange={()=>{}}><option>All categories</option></Select></Card><Card className="data-table"><table><thead><tr><th>Shelf</th><th>Zone / Product</th><th>Availability</th><th>Status</th><th>Predicted OOS</th><th>Confidence</th><th>Recommendation</th></tr></thead><tbody>{rows.map(s=><tr key={s.id} onClick={()=>setSelected(s)} tabIndex={0}><td><b>{s.id}</b></td><td><b>{s.product}</b><small>{s.zone} · {s.category}</small></td><td><div className="availability"><span><i style={{width:`${s.availability}%`}}/></span><b>{s.availability}%</b></div></td><td><StatusBadge status={s.status}/></td><td>{s.oos}</td><td>{s.confidence}%</td><td><button>{s.recommendation} →</button></td></tr>)}</tbody></table></Card><Modal open={!!selected} onClose={()=>setSelected(null)} title={`Shelf ${selected?.id} detail`}>{selected&&<ShelfDetail shelf={selected}/>}</Modal></>}
function ShelfDetail({shelf}:{shelf:Shelf}){return <div className="shelf-detail"><div className="ai-shelf"><span>LIVE EDGE ANALYSIS</span>{[1,2,3,4,5].map((x,i)=><i key={x} className={i>2?'empty':''}><b>{i<3?'DETECTED':'EMPTY'}</b></i>)}</div><div className="shelf-detail-grid"><Card><small>AVAILABILITY</small><strong>{shelf.availability}%</strong><StatusBadge status={shelf.status}/></Card><Card><small>PREDICTED OOS</small><strong>{shelf.oos}</strong><span>{shelf.confidence}% confidence</span></Card></div><Card className="analytics-card"><h3>Stock trend</h3><MiniChart type="shelf"/></Card><div className="recommend-box"><b>Recommended action</b><h3>{shelf.recommendation}</h3><p>Prioritised from availability, depletion velocity, and current store traffic.</p><DButton>Assign to staff</DButton></div></div>}
