import { ArrowRight, Clock, LogIn, LogOut, MapPin, ShieldCheck, Users } from 'lucide-react'
import { DwellChart, MiniChart } from '../../components/dashboard/Charts'
import { Card, PageHeader, SectionHeader, StatusBadge } from '../../components/dashboard/ui'
import { KpiCard } from '../../components/dashboard/KpiCard'
import { dwellData } from '../../data/shopperAnalytics'

export default function ShopperAnalytics() { return <>
  <PageHeader eyebrow="SHOPPER ANALYTICS" title="Shopper analytics" copy="Aggregate movement intelligence for store decisions — never individual identity." actions={<StatusBadge status="normal" label="Privacy protected"/>}/>
  <div className="privacy-banner"><ShieldCheck/><div><b>No face recognition or persistent customer identity.</b><span>People are counted and analyzed locally as anonymous aggregates. No names, face embeddings, or persistent IDs are stored.</span></div></div>
  <div className="compact-kpis"><KpiCard label="Total footfall" value="1,284" note="+12% vs. yesterday" icon={Users}/><KpiCard label="Entry count" value="692" note="Today" icon={LogIn}/><KpiCard label="Exit count" value="648" note="Today" icon={LogOut}/><KpiCard label="Avg dwell time" value="18m 24s" note="+4% vs. baseline" icon={Clock}/><KpiCard label="Peak hour" value="4–5 PM" note="218 visits" icon={Clock} tone="violet"/></div>
  <div className="shopper-highlight"><Card><small>MOST VISITED ZONE</small><strong>Grocery</strong><span><MapPin/> 38% of observed zone visits</span></Card><Card><small>HIGHEST DWELL ZONE</small><strong>Grocery</strong><span>5m 06s average dwell</span></Card><Card><small>ENTRY → CHECKOUT</small><strong>42.8%</strong><span>Anonymous visit conversion indicator</span></Card></div>
  <div className="analytics-layout"><Card className="analytics-card wide"><SectionHeader title="Hourly footfall" copy="Customers entering the store by hour."/><MiniChart/></Card><Card className="analytics-card"><SectionHeader title="Zone-wise dwell time" copy="Average anonymous dwell by zone."/><DwellChart data={dwellData}/></Card><Card className="analytics-card"><SectionHeader title="Movement heatmap" copy="Relative traffic concentration — not individual paths."/><div className="mini-heatmap enhanced-heatmap"><i/><i/><i/><i/><span>Entrance</span><span>Grocery</span><span>Electronics</span><span>Checkout</span><b>Higher traffic</b></div></Card></div>
  <section className="overview-section"><SectionHeader title="Entry → Browse → Checkout" copy="Aggregate same-visit funnel; counts are not linked to customer identities."/><Card className="funnel">{[['Entry','692'],['Browse','604'],['Product engagement','381'],['Checkout','296']].map(([x,v],i)=><div key={x} style={{width:`${100-i*14}%`}}><span>{x}</span><b>{v}</b>{i<3&&<ArrowRight/>}</div>)}</Card></section>
</> }
