import { useState } from 'react'
import { AnimatePresence,motion } from 'framer-motion'
import { NavLink,Outlet,useLocation } from 'react-router-dom'
import { Activity,BarChart3,Bell,ChevronLeft,CircleHelp,LayoutDashboard,Menu,PackageSearch,Search,Settings,Store,UsersRound,Wifi,X,Zap } from 'lucide-react'
import { stores } from '../../data/stores'
import { StatusBadge } from './ui'
const nav=[['Overview','/dashboard',LayoutDashboard],['Live Store','/dashboard/live-store',Store],['Shelves','/dashboard/shelves',PackageSearch],['Queues','/dashboard/queues',UsersRound],['Shopper Analytics','/dashboard/shopper-analytics',BarChart3],['Actions','/dashboard/actions',Zap],['Reports','/dashboard/reports',Activity],['Edge Health','/dashboard/edge-health',Wifi]] as const
const notifications=['Shelf A3 predicted OOS','Queue congestion increasing','Camera 3 obstructed','Action completed']
export function DashboardShell(){const [collapsed,setCollapsed]=useState(false),[drawer,setDrawer]=useState(false),[notifs,setNotifs]=useState(false),[unread,setUnread]=useState(3),[store,setStore]=useState('hyd');const location=useLocation();return <div className={`dashboard-shell ${collapsed?'collapsed':''}`}><aside className="d-sidebar"><div className="d-logo"><span>N</span><b>Niriksh</b><button onClick={()=>setCollapsed(!collapsed)} aria-label="Collapse sidebar"><ChevronLeft/></button></div><nav>{nav.map(([label,to,Icon])=><NavLink key={to} to={to} end={to==='/dashboard'} title={label}><Icon/><span>{label}</span></NavLink>)}</nav><div className="sidebar-bottom"><a href="#settings"><Settings/><span>Settings</span></a><a href="#help"><CircleHelp/><span>Help & support</span></a><div className="sidebar-profile"><span>AK</span><div><b>Arjun Kumar</b><small>Store Manager</small></div></div></div></aside><header className="d-topbar"><button className="drawer-button" onClick={()=>setDrawer(true)} aria-label="Open navigation"><Menu/></button><label className="store-select"><Store/><select value={store} onChange={e=>setStore(e.target.value)}>{stores.map(s=><option key={s.id} value={s.id}>{s.name} — {s.city}</option>)}</select></label><StatusBadge status={stores.find(s=>s.id===store)?.status??'normal'} label={store==='hyd'?'Operational':'Demo status'}/><div className="top-search"><Search/><input aria-label="Search dashboard" placeholder="Search anything..."/><kbd>⌘ K</kbd></div><div className="notification-wrap"><button className="icon-button" onClick={()=>setNotifs(!notifs)} aria-label="Notifications"><Bell/>{unread>0&&<i>{unread}</i>}</button><AnimatePresence>{notifs&&<motion.div className="notification-popover" initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}}><header><b>Notifications</b><button onClick={()=>setUnread(0)}>Mark all read</button></header>{notifications.map((n,i)=><div className={i<unread?'unread':''} key={n}><i/><span>{n}<small>{i*3+2} min ago</small></span></div>)}</motion.div>}</AnimatePresence></div><div className="top-avatar">AK</div></header><AnimatePresence>{drawer&&<><motion.div className="drawer-backdrop" onClick={()=>setDrawer(false)} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/><motion.aside className="mobile-drawer" initial={{x:'-100%'}} animate={{x:0}} exit={{x:'-100%'}}><div className="d-logo"><span>N</span><b>Niriksh</b><button onClick={()=>setDrawer(false)}><X/></button></div><nav>{nav.map(([label,to,Icon])=><NavLink key={to} to={to} end={to==='/dashboard'} onClick={()=>setDrawer(false)}><Icon/><span>{label}</span></NavLink>)}</nav></motion.aside></>}</AnimatePresence><motion.main className="dashboard-main" key={location.pathname} initial={{opacity:0,y:7}} animate={{opacity:1,y:0}} transition={{duration:.25}}><Outlet/></motion.main></div>}
