import { AnimatePresence,motion } from 'framer-motion'
import { AlertTriangle,ArrowDownRight,ArrowUpRight,ChevronDown,Search,X } from 'lucide-react'
import type { ReactNode } from 'react'
import type { Severity } from '../../types/dashboard'
export function Card({children,className='',onClick}:{children:ReactNode;className?:string;onClick?:()=>void}){return <div className={`d-card ${className}`} onClick={onClick}>{children}</div>}
export function StatusBadge({status,label}:{status:Severity;label?:string}){return <span className={`status-badge ${status}`}><i/>{label??status}</span>}
export function Trend({value,suffix='%'}:{value:number;suffix?:string}){const up=value>=0;return <span className={`trend ${up?'up':'down'}`}>{up?<ArrowUpRight/>:<ArrowDownRight/>}{Math.abs(value)}{suffix}</span>}
export function PageHeader({eyebrow,title,copy,actions}:{eyebrow?:string;title:string;copy?:string;actions?:ReactNode}){return <header className="page-header"><div>{eyebrow&&<span>{eyebrow}</span>}<h1>{title}</h1>{copy&&<p>{copy}</p>}</div>{actions&&<div className="page-actions">{actions}</div>}</header>}
export function SectionHeader({title,copy,action}:{title:string;copy?:string;action?:ReactNode}){return <div className="d-section-head"><div><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>{action}</div>}
export function DButton({children,variant='primary',onClick}:{children:ReactNode;variant?:'primary'|'secondary'|'ghost'|'danger';onClick?:()=>void}){return <button className={`d-button ${variant}`} onClick={onClick}>{children}</button>}
export function SearchInput({value,onChange,placeholder='Search'}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <label className="search-input"><Search/><span className="sr-only">{placeholder}</span><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/><kbd>⌘ K</kbd></label>}
export function Select({value,onChange,children,label}:{value:string;onChange:(v:string)=>void;children:ReactNode;label:string}){return <label className="d-select"><span className="sr-only">{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{children}</select><ChevronDown/></label>}
export function Tabs({items,value,onChange}:{items:string[];value:string;onChange:(x:string)=>void}){return <div className="tabs" role="tablist">{items.map(x=><button role="tab" aria-selected={x===value} className={x===value?'active':''} onClick={()=>onChange(x)} key={x}>{x}</button>)}</div>}
export function EmptyState({title='Nothing here yet',copy='New data will appear here when available.'}:{title?:string;copy?:string}){return <div className="state-box"><div>◇</div><h3>{title}</h3><p>{copy}</p></div>}
export function ErrorState(){return <div className="state-box error"><AlertTriangle/><h3>Couldn’t load data</h3><p>Check the connection and try again.</p><DButton>Retry</DButton></div>}
export function Skeleton(){return <div className="skeleton" aria-label="Loading"><i/><i/><i/></div>}
export function Modal({open,onClose,title,children}:{open:boolean;onClose:()=>void;title:string;children:ReactNode}){return <AnimatePresence>{open&&<motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={onClose}><motion.div role="dialog" aria-modal="true" aria-label={title} className="modal" initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:.96}} onMouseDown={e=>e.stopPropagation()}><header><h2>{title}</h2><button onClick={onClose} aria-label="Close"><X/></button></header>{children}</motion.div></motion.div>}</AnimatePresence>}
