import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App'
import './styles/index.css'
import './styles/sections.css'
import './styles/responsive.css'
import './styles/dashboard.css'
import './styles/dashboard-pages.css'
import './styles/dashboard-responsive.css'
import './styles/loader.css'
import './styles/staff.css'
import './styles/staff-detail.css'
import './styles/manager-command-center.css'
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>)
